server:
  port: 8080

spring:
  redis:
    host: 39.96.28.20
    port: 6379
    password:!QAZ1qaz
    database: 4
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4