server:
  port: 8080

spring:
  profiles:
    active: 测试
  datasource:
    name:
    password:
    url: rm-2ze693cvfg8u8k6s5mo.mysql.rds.aliyuncs.com
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 39.96.28.20
    port: 6379
    password: '!QAZ1qaz'
    database: 4
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4
logging:
  level:
    cn:
      cjy: trace

#  file: springboot.log

---
server:
  port: 8081
spring:
  profiles: 测试
  thymeleaf:
    prefix: classpath:/public/
    suffix: .html
---
server:
  port: 8081
spring:
  profiles: 正式